spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/20201220
    username: root
    password:
  jpa:
    hibernate.dll-auto: update
    generate-ddl: true
    show-sql: true